import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const INCLUDE = /^#include "([\w.-]+)"$/;
// Character pairs that would fuse into a different token if the space between them were dropped.
const FUSING = new Set([
  "++",
  "--",
  "//",
  "/*",
  "&&",
  "||",
  "<<",
  ">>",
  "==",
  "!=",
  "<=",
  ">=",
  "^^",
]);
const WORD = /[\w.]/;

const DEFINE = /^#\s*define\s+(\w+)(\s*)(.*)$/;
const COMMENT = /\/\/[^\n]*|\/\*[\s\S]*?\*\//g;

/**
 * Removes `//` and `/* *\/` comments in one left-to-right pass, so whichever
 * opens first wins, as in the GLSL lexer. A block comment becomes a space, or
 * the newlines it spanned, since GLSL keeps those. GLSL has no string literals,
 * so there is no quoting to respect.
 */
export function stripComments(src: string): string {
  return src.replace(COMMENT, (c) => (c.startsWith("//") ? "" : c.replace(/[^\n]/g, "") || " "));
}

// Drops whitespace between tokens except where two word characters (or a fusing pair) meet, which keep one space.
function squeeze(line: string): string {
  let out = "";
  let pendingSpace = false;
  for (const ch of line) {
    if (/\s/.test(ch)) {
      pendingSpace = out !== "";
      continue;
    }
    if (pendingSpace) {
      const prev = out.slice(-1);
      if ((WORD.test(prev) && WORD.test(ch)) || FUSING.has(prev + ch)) out += " ";
      pendingSpace = false;
    }
    out += ch;
  }
  return out;
}

// Whitespace right after a macro's name is meaningful: `#define F (x)` is object-like and `#define N -1` must not become `N-1`.
function directive(line: string): string {
  const m = DEFINE.exec(line);
  if (m === null) return squeeze(line);
  const [, name = "", space = "", body = ""] = m;
  return `#define ${name}${body !== "" && space !== "" ? " " : ""}${squeeze(body)}`;
}

/**
 * Strips comments and redundant whitespace, nothing else: identifiers and
 * numeric literals are left exactly as written. Preprocessor directives keep
 * their own lines, as GLSL requires.
 */
export function minifyGlsl(src: string): string {
  let out = "";
  let body = "";
  const flush = (): void => {
    const s = squeeze(body);
    if (s !== "") out += s;
    body = "";
  };
  for (const raw of stripComments(src).split("\n")) {
    const line = raw.trim();
    if (line.startsWith("#")) {
      flush();
      if (out !== "" && !out.endsWith("\n")) out += "\n";
      out += `${directive(line)}\n`;
    } else if (line !== "") {
      body += ` ${line}`;
    }
  }
  flush();
  return out;
}

/** Replaces each `#include "file"` line with that file's text, read through `read`. Includes do not nest. */
export function resolveIncludes(src: string, read: (file: string) => string): string {
  return src
    .split("\n")
    .map((line) => {
      const m = INCLUDE.exec(line.trim());
      return m?.[1] === undefined ? line : read(m[1]);
    })
    .join("\n");
}

/** `sky.frag.glsl` becomes `SKY_FS`; files without a stage (shared includes) are skipped. */
export function exportName(file: string): string | undefined {
  const m = /^([\w-]+)\.(vert|frag)\.glsl$/.exec(file);
  if (m?.[1] === undefined) return undefined;
  return `${m[1].toUpperCase().replace(/-/g, "_")}_${m[2] === "vert" ? "VS" : "FS"}`;
}

/** Builds every program source in `dir`, keyed by export name, in file-name order. */
export function buildShaders(dir: string): Map<string, string> {
  const read = (file: string): string => readFileSync(`${dir}/${file}`, "utf8");
  const programs = new Map<string, string>();
  for (const file of readdirSync(dir).sort()) {
    const name = exportName(file);
    if (name !== undefined) programs.set(name, minifyGlsl(resolveIncludes(read(file), read)));
  }
  return programs;
}

export function renderModule(programs: ReadonlyMap<string, string>): string {
  let out = "// Generated by scripts/shaders.ts from src/shaders/*.glsl. Do not edit.\n";
  for (const [name, source] of programs)
    out += `export const ${name}: string = ${JSON.stringify(source)};\n`;
  return out;
}

/**
 * Regenerates `src/shaders/generated.ts`, writing only when the text changed
 * so that a watching test runner does not see a spurious edit.
 */
export function writeShaders(): void {
  const dir = fileURLToPath(new URL("../src/shaders", import.meta.url));
  const file = `${dir}/generated.ts`;
  const text = renderModule(buildShaders(dir));
  if (!existsSync(file) || readFileSync(file, "utf8") !== text) writeFileSync(file, text);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) writeShaders();
